version: '3'

networks:
  traefik:

services:
  beans-coatings-api:
    container_name: beans-coatings-api
    hostname: beans-coatings-api
    build:
      context: ../../
      dockerfile: build/Dockerfile  
    env_file: .env.dev
    ports:
      - 5000:5000
    networks:
      - traefik
